name: Android build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Run test
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build